name: CI/CD
on:
  push:
    paths:
      - "backend/**"

jobs:
  backend-CI:
    runs-on: ubuntu-latest
    # services:
    #   mariadb:
    #     image: mariadb
    #     env:
    #       MYSQL_DATABASE: test_db
    #       MYSQL_USER: test_user
    #       MYSQL_PASSWORD: test_password
    #       MYSQL_ROOT_PASSWORD: test_password
    #     ports:
    #       - 3310:3306
    #     options: >-
    #       --health-cmd "mysqladmin status -h 127.0.0.1 -P 3306 -u root -p$MYSQL_ROOT_PASSWORD"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 6

    steps:
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3310 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: "utf8" # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: "utf8_general_ci" # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: "latest" # Optional, default value is "latest". The version of the MariaDB
          mysql database: "test_db" # Optional, default value is "test". The specified database which will be create
          mysql root password: "test_password" # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: "test_user" # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: "test_password" # Required if "mysql user" exists. The password for the "mysql user"

      - name: 체크아웃
        uses: actions/checkout@v2
      - name: DB에 샘플 데이터 삽입
        run: >-
          mysql --force
          --host="127.0.0.1"
          --port="3310"
          --database="test_db"
          --user="test_user"
          --password="test_password"
          < "backend/src/test/resources/database/spring_test_db.sql"

      - name: JDK 11 설정
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "amazon-corretto"

      - name: Gradle 빌드
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew build
        shell: bash

  backend-CD-develop:
    name: deploy-develop
    runs-on: ubuntu-latest
    needs: [backend-CI]
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: 리모트 쉘 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_NEW }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            source $HOME/.bash_profile
            echo "해당 리포지토리로 이동"
            cd $HOME/42cabi_dev
            echo "리포지토리 pull"
            git pull origin dev
            echo "앱 빌드"
            cd $HOME/42cabi_dev/backend
            npm install
            npm run build
            echo "env 파일 복사"
            cp $HOME/42cabi_dev.env $HOME/42cabi_dev/backend/.env
            echo "앱 배포 (reload)"
            pm2 reload cabi_dev

  backend-CD-main:
    name: deploy-main
    runs-on: ubuntu-latest
    needs: [backend-CI]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: 리모트 쉘 접속
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_MAIN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_NEW }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            source $HOME/.bash_profile
            echo "해당 리포지토리로 이동"
            cd $HOME/42cabi_main
            echo "리포지토리 pull"
            git pull origin main
            echo "앱 빌드"
            cd $HOME/42cabi_main/backend
            npm install
            npm run build
            echo "env 파일 복사"
            cp $HOME/42cabi_main.env $HOME/42cabi_main/backend/.env
            echo "앱 배포 (reload)"
            pm2 reload cabi_main
